apiVersion: react/v1
kind: Deployment
metadata:
  name:  react-ui
  namespace: default
  labels:
    app:  react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  react-ui
    spec:
    containers:
    - name:  react-ui
      image:  MYAPP:latest
      ports:
      - containerPort:  8080
        name:  react-ui


       ####################################### 

apiVersion: v1
kind: Service
metadata:
  name: react-netflix
  namespace: default
spec:
  selector:
    app: react-netflix
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: react-netflix
    protocol: TCP
    port: 
    targetPort: 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 
