apiVersion: react/v1
kind: Deployment
metadata:
  name:  react-ui
  namespace: default
  labels:
    app:  react-ui
spec:
  selector:
    matchLabels:
      app: react-ui
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  react-ui
    spec:
    containers:
    - name:  react-ui
      image:  MYAPP:latest
      ports:
      - containerPort:  8080
        name:  react-ui